apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    role: frontend
  name: frontend
  namespace: network-test
spec:
  containers:
    - image: nginx:1.23
      name: frontend
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    role: backend
  name: backend
  namespace: network-test
spec:
  containers:
    - image: busybox
      name: backend
      command: ["sleep", "3600"]
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-access
  namespace: network-test
spec:
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 80
