apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: network-test
  labels:
    role: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.23
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: network-test
  labels:
    app: backend
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    ports:
    - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-access
  namespace: network-test
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - protocol: TCP
      port: 80