apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: config-secret-deploy
data:
  APP_ENV: production
  APP_DEBUG: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: config-secret-deploy
data:
  DB_USER: YWRtaW4= 
  DB_PASSWORD: cGFzc3dvcmQxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-secret-deploy
  labels:
    app: config-secret-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-secret-deploy
  template:
    metadata:
      labels:
        app: config-secret-deploy
    spec:
      containers:
      - name: config-secret-container
        image: nginx:latest
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_DEBUG
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
