ammar@LOKI:~$ k apply -f deployment-service.yaml -n production
service/web-service created
ammar@LOKI:~$ k get pods
No resources found in default namespace.
ammar@LOKI:~$ k get deployments.apps -n production
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
web-deployment   1/3     3            1           64s
ammar@LOKI:~$ k get service -n production
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
web-service   ClusterIP   10.101.187.31   <none>        80/TCP    41s

##web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-deployment
  name: web-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-deployment
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

##web-service.yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-01-10T13:29:19Z"
  labels:
    app: web-deployment
  name: web-service
  namespace: production
  resourceVersion: "6144"
  uid: 4dae407a-56be-4d64-84ff-ebb00ee05a0e
spec:
  clusterIP: 10.101.187.31
  clusterIPs:
  - 10.101.187.31
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}