apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  ports:
  - port: 5432
    name: db-statefulset
  clusterIP: None
  selector:
    app: db-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  selector:
    matchLabels:
      app: db-statefulset # has to match .spec.template.metadata.labels
  serviceName: "db-service"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: db-statefulset # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
          name: db-statefulset
        volumeMounts:
        - name: www
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "fast-storage"
      resources:
        requests:
        requests:
          storage: 5Gi
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: rancher.io/local-path
parameters:
  type: pd-standard
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer