kubectl label nodes node01 env=production
kubectl taint node node01 dedicated=critical:NoSchedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: critical-app
  name: critical-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: critical-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: critical-app
    spec:
      containers:
        - image: busybox
          name: busybox
          command: ["sleep", "3600"]
          resources: {}
      nodeSelector:
        env: production
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "critical"
          effect: "NoSchedule"
status: {}
